# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'FoodFindr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for testingSignIn
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Invites'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'GoogleSignIn'
  
  target 'FoodFindrTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'FoodFindrUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
# target 'FoodFindr WatchKit App' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Pods for FoodFindr WatchKit App

# end

# target 'FoodFindr WatchKit Extension' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
# use_frameworks!

# Pods for FoodFindr WatchKit Extension

# end
